import { useState, useEffect, useRef } from "react";
const saveMemory = async () => {};
const ActivityLog = () => <div style={{padding:"24px",color:"#888",fontSize:"14px"}}>📡 Activity Log — coming soon.</div>;
const C = {black:"#0A0A0A",charcoal:"#141414",panel:"#1A1A1A",border:"#2A2A2A",accent:"#FF6B2B",accentD:"#CC5520",accentG:"linear-gradient(135deg,#FF6B2B,#FF9A5C)",gold:"#F5A623",green:"#22C55E",red:"#EF4444",blue:"#3B82F6",purple:"#A855F7",teal:"#14B8A6",cyan:"#06B6D4",text:"#F0F0F0",muted:"#888",faint:"#333"};
const AGENTS=[
{id:"scout",name:"SCOUT",title:"Lead Intelligence Agent",emoji:"🔍",color:C.blue,status:"ACTIVE",focus:"Sales & Marketing",description:"Researches and identifies new prospects across fit-out, signage, refurbishment, and construction sectors.",capabilities:["Prospect research","Contact discovery","Industry scanning","Competitor intel","Market mapping"],systemPrompt:"You are SCOUT, Brandboy's Lead Intelligence Agent. Brandboy is an Australian commercial construction, fit-out, signage, and refurbishment company. Your job is to help identify, research, and build targeted prospect lists across Australia."},
{id:"writer",name:"COMPOSER",title:"Email & Outreach Agent",emoji:"✍️",color:C.purple,status:"ACTIVE",focus:"Sales & Marketing",description:"Drafts personalised outreach emails, follow-ups, and campaign sequences for Lars to approve.",capabilities:["Email campaigns","Follow-up sequences","Proposal drafts","LinkedIn outreach","SMS scripts"],systemPrompt:"You are COMPOSER, Brandboy's Email & Outreach Agent. You write compelling, professional outreach emails to be sent from team@brandboy.com.au. Always write in a confident, professional but approachable Australian tone."},
{id:"hunter",name:"HUNTER",title:"Project Opportunity Agent",emoji:"🎯",color:C.green,status:"ACTIVE",focus:"Business Development",description:"Scans for live tenders, government contracts, DA approvals, and project opportunities.",capabilities:["Tender alerts","DA tracking","Govt contracts","Retail pipeline","Property intel"],systemPrompt:"You are HUNTER, Brandboy's Project Opportunity Agent. Your job is to identify active project opportunities including government tenders, DA approvals, retail expansion, and corporate relocations. Flag high-value opportunities over $500K as PRIORITY."},
{id:"ops",name:"OPS",title:"Operations & Backup Agent",emoji:"⚙️",color:C.gold,status:"ACTIVE",focus:"Operations",description:"Manages internal processes, client follow-ups, supplier coordination, and job costing support.",capabilities:["Process automation","Data backup logs","Supplier comms","Job tracking","Risk flags"],systemPrompt:"You are OPS, Brandboy's Operations & Backup Agent. Your job is to support smooth operations including tracking active jobs, flagging overdue client responses, drafting supplier communications, and maintaining process checklists."},
{id:"seo",name:"RANKR",title:"SEO & Digital Visibility Agent",emoji:"📈",color:C.teal,status:"ACTIVE",focus:"Marketing & Digital",description:"Owns brandboy.com.au organic search performance.",capabilities:["Keyword research","Page audits","Content briefs","Meta optimisation","Local SEO","Blog strategy","Backlink intel"],systemPrompt:"You are RANKR, Brandboy's SEO Agent. Maximise Brandboy's organic search visibility across Google Australia."},
{id:"crm",name:"NEXUS",title:"CRM & Pipeline Agent",emoji:"🗂️",color:C.cyan,status:"ACTIVE",focus:"Sales Operations",description:"Manages Brandboy's entire client and prospect pipeline.",capabilities:["Pipeline tracking","Lead scoring","Contact segmentation","Deal stage mgmt","Follow-up alerts","Win/loss analysis","Client retention"],systemPrompt:"You are NEXUS, Brandboy's CRM & Pipeline Management Agent. Your job is to manage the full client and prospect lifecycle, pipeline stages, lead scoring, and weekly reporting."},
{id:"forge",name:"FORGE",title:"AI Developer Agent",emoji:"🔧",color:"#F97316",status:"ACTIVE",focus:"Technology & Build",description:"Brandboy's in-house AI developer. Builds, fixes, and ships code for Mission Control.",capabilities:["React development","Bug fixing","Feature builds","API integration","Code review","Deployment"],systemPrompt:"You are FORGE, Brandboy's AI Developer Agent. You build and maintain Mission Control. You write clean React code, fix bugs, and ship working solutions fast."}
];
const QUICK_TASKS={scout:["Find 5 retail chains in NSW due for a store refresh","Research top 10 franchise networks expanding in 2025","Find facility managers in Sydney CBDs managing 50+ sites","Identify corporates relocating offices in Melbourne"],writer:["Draft a cold outreach email for a national pharmacy chain","Write a 3-email follow-up sequence for signage prospects","Create a LinkedIn message for a property developer","Draft a re-engagement email for a past Brandboy client"],hunter:["Find active government tenders for commercial fit-out","Scan for DA approvals for commercial builds in Sydney","Identify retail brands announcing new store openings","Find corporate office relocations announced this quarter"],ops:["Create a weekly ops checklist for project managers","Draft a supplier follow-up email template","Build a risk register for a new fit-out project","Summarise what data Brandboy should be backing up daily"],seo:["Find the top 10 keywords Brandboy should rank for","Audit the brandboy.com.au homepage for SEO issues","Write an SEO blog post on office fit-out trends in Sydney","Create a local SEO strategy for Brandboy in NSW, VIC, QLD"],crm:["Build a lead scoring template for Brandboy prospects","Create a 6-stage pipeline structure for fit-out deals","Draft a weekly pipeline report template for Lars","Segment our contacts by service line and deal value"]};
async function askAgent(agent,messages){const res=await fetch("/api/ask-agent",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({systemPrompt:agent.systemPrompt,messages})});const data=await res.json();if(data.error)throw new Error(data.error.message||data.error);return data.content.map(b=>b.text||"").join("");}
function StatusPill({status,color}){return <span style={{background:color+"22",color,border:`1px solid ${color}44`,borderRadius:4,fontSize:10,fontWeight:700,padding:"2px 8px",letterSpacing:1}}>{status}</span>;}
function AgentCard({agent,onClick,active}){return(<div onClick={()=>onClick(agent)} style={{background:active?agent.color+"15":"#1A1A1A",border:`1px solid ${active?agent.color:"#2A2A2A"}`,borderRadius:10,padding:"14px 16px",cursor:"pointer",transition:"all 0.2s",position:"relative",overflow:"hidden"}}>{active&&<div style={{position:"absolute",top:0,left:0,right:0,height:2,background:agent.color}}/>}<div style={{display:"flex",alignItems:"center",gap:10,marginBottom:8}}><span style={{fontSize:22}}>{agent.emoji}</span><div><div style={{fontWeight:800,fontSize:13,color:agent.color,letterSpacing:1}}>{agent.name}</div><div style={{fontSize:10,color:"#888"}}>{agent.title}</div></div><StatusPill status={agent.status} color={agent.color}/></div><div style={{fontSize:11,color:"#888",lineHeight:1.5}}>{agent.description}</div><div style={{marginTop:10,display:"flex",flexWrap:"wrap",gap:4}}>{agent.capabilities.map(c=><span key={c} style={{fontSize:9,background:"#333",color:"#888",borderRadius:3,padding:"2px 6px"}}>{c}</span>)}</div><div style={{marginTop:8,fontSize:10,color:agent.color+"99"}}>Focus: {agent.focus}</div></div>);}
function ChatBubble({msg}){const isUser=msg.role==="user";return(<div style={{display:"flex",justifyContent:isUser?"flex-end":"flex-start",marginBottom:12}}>{!isUser&&<div style={{width:30,height:30,borderRadius:"50%",background:msg.agentColor+"22",border:`1px solid ${msg.agentColor}44`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:14,marginRight:8,flexShrink:0}}>{msg.agentEmoji}</div>}<div style={{maxWidth:"75%",background:isUser?"#FF6B2B":"#1A1A1A",border:`1px solid ${isUser?"#CC5520":"#2A2A2A"}`,borderRadius:isUser?"14px 14px 4px 14px":"14px 14px 14px 4px",padding:"10px 14px",fontSize:13,color:"#F0F0F0",lineHeight:1.6,whiteSpace:"pre-wrap"}}>{!isUser&&<div style={{fontSize:10,color:msg.agentColor,fontWeight:700,marginBottom:4,letterSpacing:1}}>{msg.agentName}</div>}{msg.content}{msg.pending&&<span style={{display:"inline-flex",gap:3,marginLeft:6}}>{[0,1,2].map(i=><span key={i} style={{width:5,height:5,borderRadius:"50%",background:"#888",animation:`pulse 1.2s ${i*0.2}s ease-in-out infinite`}}/>)}</span>}</div>{isUser&&<div style={{width:30,height:30,borderRadius:"50%",background:"#FF6B2B22",border:"1px solid #CC5520",display:"flex",alignItems:"center",justifyContent:"center",fontSize:12,fontWeight:800,color:"#FF6B2B",marginLeft:8,flexShrink:0}}>L</div>}</div>);}
function QuickTaskButton({label,onClick}){return<button onClick={onClick} style={{background:"#333",border:"1px solid #2A2A2A",color:"#888",borderRadius:6,padding:"6px 12px",fontSize:11,cursor:"pointer",whiteSpace:"nowrap"}} onMouseEnter={e=>{e.target.style.borderColor="#FF6B2B";e.target.style.color="#FF6B2B"}} onMouseLeave={e=>{e.target.style.borderColor="#2A2A2A";e.target.style.color="#888"}}>{label}</button>;}
export default function MissionControl(){
const [activeAgent,setActiveAgent]=useState(AGENTS[0]);
const [conversations,setConversations]=useState({scout:[],writer:[],hunter:[],ops:[],seo:[],crm:[],forge:[]});
const [input,setInput]=useState("");
const [loading,setLoading]=useState(false);
const [view,setView]=useState("chat");
const [time,setTime]=useState(new Date());
const chatEndRef=useRef(null);
useEffect(()=>{const t=setInterval(()=>setTime(new Date()),1000);return()=>clearInterval(t);},[]);
useEffect(()=>{chatEndRef.current?.scrollIntoView({behavior:"smooth"});},[conversations,loading]);
const msgs=conversations[activeAgent.id]||[];
async function send(text){if(!text.trim()||loading)return;const userMsg={role:"user",content:text};const newMsgs=[...msgs,userMsg];setConversations(c=>({...c,[activeAgent.id]:newMsgs}));setInput("");setLoading(true);setConversations(c=>({...c,[activeAgent.id]:[...newMsgs,{role:"assistant",content:"",pending:true,agentName:activeAgent.name,agentColor:activeAgent.color,agentEmoji:activeAgent.emoji}]}));try{const apiMsgs=newMsgs.map(m=>({role:m.role,content:m.content}));const reply=await askAgent(activeAgent,apiMsgs);await saveMemory(activeAgent.name,"task",`User: ${text}\n\n${activeAgent.name}: ${reply}`,[activeAgent.focus,activeAgent.id]);setConversations(c=>{const cur=c[activeAgent.id].filter(m=>!m.pending);return{...c,[activeAgent.id]:[...cur,{role:"assistant",content:reply,agentName:activeAgent.name,agentColor:activeAgent.color,agentEmoji:activeAgent.emoji}]};});}catch(err){setConversations(c=>{const cur=c[activeAgent.id].filter(m=>!m.pending);return{...c,[activeAgent.id]:[...cur,{role:"assistant",content:`⚠️ Error: ${err.message}`,agentName:activeAgent.name,agentColor:activeAgent.color,agentEmoji:activeAgent.emoji}]};});}setLoading(false);}
const quickTasks=QUICK_TASKS[activeAgent.id]||[];return(<div style={{minHeight:"100vh",background:"#0A0A0A",color:"#F0F0F0",fontFamily:"'Inter',system-ui,sans-serif",display:"flex",flexDirection:"column"}}>
<style>{`*{box-sizing:border-box;}::-webkit-scrollbar{width:4px;}::-webkit-scrollbar-track{background:#141414;}::-webkit-scrollbar-thumb{background:#333;border-radius:2px;}@keyframes pulse{0%,100%{opacity:0.3;transform:scale(0.8);}50%{opacity:1;transform:scale(1.1);}}textarea:focus{outline:none;}button:active{transform:scale(0.97);}`}</style>
<div style={{background:"#141414",borderBottom:"1px solid #2A2A2A",padding:"0 24px",height:56,display:"flex",alignItems:"center",justifyContent:"space-between",flexShrink:0}}>
<div style={{display:"flex",alignItems:"center",gap:16}}>
<div style={{background:"linear-gradient(135deg,#FF6B2B,#FF9A5C)",borderRadius:8,padding:"4px 12px",fontWeight:900,fontSize:15,letterSpacing:1}}>BB</div>
<div><div style={{fontWeight:800,fontSize:14,letterSpacing:0.5}}>BRANDBOY MISSION CONTROL</div><div style={{fontSize:10,color:"#888",letterSpacing:1}}>AI AGENT COMMAND CENTRE · SYDNEY AU</div></div>
</div>
<div style={{display:"flex",alignItems:"center",gap:20}}>
<div style={{display:"flex",alignItems:"center",gap:6}}><div style={{width:7,height:7,borderRadius:"50%",background:"#22C55E",animation:"pulse 2s ease-in-out infinite"}}/><span style={{fontSize:11,color:"#22C55E",fontWeight:700}}>7 AGENTS LIVE</span></div>
<div style={{fontSize:12,color:"#888"}}>{time.toLocaleTimeString("en-AU",{hour:"2-digit",minute:"2-digit",second:"2-digit"})}</div>
</div>
</div>
<div style={{background:"#141414",borderBottom:"1px solid #2A2A2A",padding:"0 24px",display:"flex",gap:0,flexShrink:0}}>
{[["chat","💬 Talk to Agent"],["agents","🤖 All Agents"],["strategy","📋 Strategy"],["activity","📡 Activity Log"]].map(([v,label])=><button key={v} onClick={()=>setView(v)} style={{background:"none",border:"none",borderBottom:view===v?"2px solid #FF6B2B":"2px solid transparent",color:view===v?"#FF6B2B":"#888",padding:"10px 20px",fontSize:12,fontWeight:view===v?700:400,cursor:"pointer",letterSpacing:0.5}}>{label}</button>)}
</div>
<div style={{flex:1,display:"flex",overflow:"hidden"}}>
<div style={{width:260,background:"#141414",borderRight:"1px solid #2A2A2A",padding:"16px 12px",overflowY:"auto",flexShrink:0,display:"flex",flexDirection:"column",gap:8}}>
<div style={{fontSize:10,color:"#888",letterSpacing:1,padding:"0 4px",marginBottom:4}}>SELECT AGENT</div>
{AGENTS.map(a=><AgentCard key={a.id} agent={a} onClick={ag=>{setActiveAgent(ag);setView("chat");}} active={activeAgent.id===a.id}/>)}
<div style={{marginTop:"auto",background:"#1A1A1A",border:"1px solid #2A2A2A",borderRadius:8,padding:"10px 
